addons:
  apt:
    packages:
      - zsh
      - ncurses-dev
      - autoconf
      - yodl
      - man
cache:
  apt: true
  directories:
    - $HOME/.zvm
dist: trusty
matrix:
  include:
    - env: ZVM_VERSION='5.0.8'
    - env: ZVM_VERSION='5.1.1'
    - env: ZVM_VERSION='5.2'
    - env: ZVM_VERSION='5.3.1'
install:
  - if [[ $(ls "$HOME/.zvm" | wc -l) -eq 0 ]]; then rm -rf "$HOME/.zvm"; fi
  - mkdir .bin
  - curl -L https://raw.githubusercontent.com/molovo/revolver/master/revolver > .bin/revolver
  - curl -L https://raw.githubusercontent.com/molovo/color/master/color.zsh > .bin/color
  - curl -L https://raw.githubusercontent.com/molovo/zvm/master/zvm > .bin/zvm
  - curl -L https://github.com/molovo/zunit/releases/download/v0.7.0/zunit > .bin/zunit
  - chmod u+x .bin/{color,revolver,zunit,zvm}
  - export PATH="$HOME/.zvm/bin:$PWD/.bin:$PATH"
before_script:
  - zvm use ${ZVM_VERSION}
  - ./build.zsh
script: zunit
notifications:
  email: false
